name: Feature request
description: Suggest an idea or improvement
labels: ["enhancement"]
body:
  - type: dropdown
    id: addon
    attributes:
      label: Target add-on
      options:
        - Caddy mTLS Proxy
        - "(Repository-wide / new add-on)"
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
